#!/bin/bash

cd ~

dateNow=$(date +%Y-%m-%d) 

#for i in $(ls | grep "^Backup-" | sort -n )
#do
#echo $i
#done

datePrev=$(ls | grep "^Backup-" | sort -n | tail -1 | cut -d "-" -f 2,3,4)

if [[ $( echo $(date -d $dateNow +%s) $(date -d $datePrev +%s) | awk '{print ($1 - $2) / 60 / 60 / 24}') -ge 7 ]] 
then
	mkdir "Backup-$dateNow"
	cd ~/source 
	ArrayListFilesInSource=$(ls)
	for currentFile in $ArrayListFilesInSource
	do
		cp -R $currentFile ~/Backup-$dateNow		
	done
	cd ~
	echo "Directory Backup-$dateNow was created."
	echo "Files: $ArrayListFilesInSource" >> backup-report	
else
	cd ~/source 
	ArrayListFilesInSource=$(ls)
	cd ~
	echo "Directory Backup-$datePrev was created."
	echo "Files: $ArrayListFilesInSource" >> backup-report	
	cd ~/Backup-$datePrev
	for currentFile in $ArrayListFilesInSource
	do
		if [[ -f $currentFile ]]
		then
			sizeSourceFile=$(ls -l ~/source/$currentFile | awk '{print$5}')
			sizeBackupFile=$(ls -l $currentFile | awk '{print$5}')
			if [[ $sizeSourceFile -ne $sizeBackupFile ]]
			then 
				mv $currentFile $currentFile-$dateNow
				cp -R ~/source/$currentFile ~/Backup-$datePrev
				echo "rename $currentFile to $currentFile-$dateNow" >> ~/backup-report
			fi
		else
			cp -R ~/source/$i ~/Backup-$dateFiles
		fi		
	done
fi




	
		
