#!/bin/bash

if [[ $# -ne 1 ]] 
then  
	exit 1
fi

FileName=$1

trashLog=~/trash.log

echo "" > $trashLog

for string in $(cat $trashLog)
do
	if [[ $string =~ $FileName ]]
	then 
		echo "Do you want to restore the $string file?"
		echo "Our answer yes/no"
		read answer 
		if [[ $answer == "yes" ]] 
		then	
			cd ~/trash 
			fileInTrash="$( echo "$string" | cut -d "=" -f 2 )"
			mycd="$(echo "$string" | cut -d "=" -f 1 | grep -oP ".*/")"
			if [[ ! -d $mycd ]]
			then
				ln $fileInTrash ~/$FileName
				rm $fileInTrash
			else 
				if [[ ! -f $mycd$FileName ]] 
				then
					ln "$fileInTrash" "$mycd$FileName"
					rm "$fileInTrash"
				else 
					echo "This file already exists."
					echo "Do you want to rename and restore?"
					echo "Our answer yes/no"
					read answer
					if [[ $answer = "yes" ]]
					then 
						read newName
						ln $fileInTrash $mycd$newName
						rm $fileInTrash
					fi	
				fi	
			fi		
		fi
	else $string >> $trashLog			
	fi 
done
	
