#!/bin/bash
cnt=0
vector=()
echo "" > report1.log
echo "" > report1.txt
while true
do
vector+=(1 2 3 4 5 6 7 8 9 10)
cnt=$(($cnt + 1))
if [[ $cnt == "100000" ]] 
then 
./help
echo ${#vector[*]} >> report1.log
cnt=0
fi
done

