#!/bin/bash
./iv_script
rm answer5
touch answer5
N=0
M=0
count=0
while read string 
do
tempPPid=$(echo $string | grep -E -o 'Parent_ProcessID= [[:digit:]]+' | grep -E -o [[:digit:]]+)
if [[ $N -eq  $tempPPid ]]
then
	count=$(echo $count | awk '{print $1+1}');
	current=$(echo $string | grep -E -o 'Average_Running_Time= [[:digit:]]+[,[:digit:]]*' | grep -E -o [[:digit:]]+[,[:digit:]]*)
	M=$(echo $M $current | awk '{print $1+$2}')
else 
	M=$(echo $M $count | awk '{print $1/$2}')
	echo 'Average_Sleeping_Children_of_ParentID=' $N ' is ' $M >> answer5
	N=$(echo $string | grep -E -o 'Parent_ProcessID= [[:digit:]]+' | grep -E -o [[:digit:]]+)
	M=$(echo $string | grep -E -o 'Average_Running_Time= [[:digit:]]+[,[:digit:]]*' | grep -E -o [[:digit:]]+[,[:digit:]]*)
	count=1
fi
echo $string >> answer5
done < answer4
M=$(echo $M $count | awk '{print $1/$2}')
echo 'Average_Sleeping_Children_of_ParentID=' $N ' is ' $M >> answer5
