#!/bin/bash
echo $$ > .pid
A=1
oper="wait operation"
usr1()
{
	oper="+"
}
usr2()
{
	oper="*"
}
usr3()
{
	oper="-"
}
usr4()
{
	A=$(cat number)
}


trap 'usr1' USR1
trap 'usr2' USR2
trap 'usr3' SIGABRT
trap 'usr4' SIGALRM
while true
do
	case $oper in 
	"+"	)
	let A=$A+2
	echo $A ;;
	
	"*"	)
	let A=$A\*2
	echo $A ;;
	
	"-"	)
	let A=$A-2
	echo $A ;;
	
	"wait operation"	)
	
	echo "wait operation" ;;
	
	esac
	
	sleep 1
done
