#!/bin/bash
mkfifo pipe
re='^[0-9]+$'
while true; do
	read LINE
	echo "$LINE" > pipe
	if [[ $LINE == "QUIT" ]] 
		then 
		break
	fi
	if ! [[ $LINE =~ $re ]] ; then
   		echo "error: Not a number";
   		break;
	fi
done
